project:
  type: book
  output-dir: docs

book:
  title: "rd3c3_guide"
  author: "Sandoval-Hernández, Carrasco & Eryılmaz"
  date: "12/14/2024"
  chapters:
    - index.qmd
    - introduction.qmd
    - section_1_response_model.qmd
    - section_2_partial.qmd
    - section_3_rd3c3.qmd
    - section_4_example.qmd
    - section_5_intended_use.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

