project:
  type: book
  output-dir: docs

book:
  title: "PSI2301 Apuntes de clases"
  author: "https://dacarras.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - introduction.qmd
    - section_1_response_model.qmd
    - section_2_partial.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

